### ISSUE TITLE
Detect os and use tesseract.exe in windows environment

### ISSUE THREAD

**Issue by a443833359** [jflesch/pyocr#31]
I'm a windows user and when using this module it can't detect my tesseract, after reading the source I found in windows we should use tesseract.exe instead of tesseract as TESSERACT_PATH.

I think detect os and use tesseract.exe in windows environment will surely decrease the pain of windows users, or at least write something like FAQ in readme will be good.

**Comment by jflesch** [comment]
As stated in the README, PyOCR has only been tested on GNU/Linux. I haven't tried, but I would guess it doesn't work at all with Windows and MacOSX.

If you want to port it to Windows, feel free to do it. I'll gladly accept any patch for that that doesn't break GNU/Linux support.
I can't do it myself because I don't have any Windows license.
